variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  FF_NETWORK_PER_BUILD: "true"

stages:
  - build
  - manifest

.base_job: &base_job
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      variables:
        TAG_SUFFIX: "-mr${CI_MERGE_REQUEST_IID}"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""

build:
  <<: *base_job
  stage: build
  image: docker:latest@sha256:f80c26212befc1c1988b529495532c6b9180d9b1dab1611f4a1efbe9da8ec821
  tags:
    - $RUNNER_TAG
  before_script:
    - apk update
    - apk add bash git
  script:
    - if [ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]; then
        docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}";
      fi
    - ./bin/build.sh
  parallel:
    matrix:
      - ARCH: amd64
        RUNNER_TAG: thelab-amd64
      - ARCH: arm64
        RUNNER_TAG: thelab-arm64

manifest:
  stage: manifest
  tags:
    - thelab-arm64
  needs: [build]
  image: docker:latest@sha256:f80c26212befc1c1988b529495532c6b9180d9b1dab1611f4a1efbe9da8ec821
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_REF_PROTECTED == "true"
      variables:
        TAG_SUFFIX: ""
  script:
    - apk update
    - apk add bash git
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_JOB_TOKEN}" "${CI_REGISTRY}"
    - ./bin/push-manifest.sh
